In [33]:
from keras import Sequential
from keras.layers import Dense,SimpleRNN

In [34]:
model=Sequential()

model.add(SimpleRNN(3,input_shape=(4,5)))
model.add(Dense(1,activation='sigmoid'))

model.summary()

Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_1 (SimpleRNN)    (None, 3)                 27        
                                                                 
 dense_1 (Dense)             (None, 1)                 4         
                                                                 
Total params: 31 (124.00 Byte)
Trainable params: 31 (124.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [35]:
print(model.get_weights()[0].shape)
model.get_weights()[0]

(5, 3)


array([[ 0.66838604, -0.7426205 , -0.6517905 ],
       [ 0.41452187,  0.18339282,  0.23603266],
       [ 0.4954186 ,  0.42186373,  0.29213172],
       [-0.27925867, -0.7311322 , -0.2635107 ],
       [ 0.3834358 , -0.72578835,  0.06335402]], dtype=float32)

In [36]:
print(model.get_weights()[1].shape)
model.get_weights()[1]

(3, 3)


array([[-0.15854514, -0.56216156, -0.81168836],
       [ 0.83581895,  0.3612197 , -0.4134332 ],
       [-0.52561396,  0.74397236, -0.41259557]], dtype=float32)

In [37]:
print(model.get_weights()[2].shape)
model.get_weights()[2]

(3,)


array([0., 0., 0.], dtype=float32)

In [38]:
print(model.get_weights()[3].shape)
model.get_weights()[3]

(3, 1)


array([[-0.59324837],
       [-0.24050361],
       [-0.08106792]], dtype=float32)

In [39]:
print(model.get_weights()[4].shape)
model.get_weights()[4]

(1,)


array([0.], dtype=float32)

In [40]:
import numpy as np
docs=['go home','come back','go to school','india won the match','i am happy','dhoni is king']

In [41]:
from keras.preprocessing.text import Tokenizer
tokenizer =Tokenizer(oov_token='<nothing>')

In [42]:
tokenizer.fit_on_texts(docs)

In [43]:
tokenizer.word_index

{'<nothing>': 1,
 'go': 2,
 'home': 3,
 'come': 4,
 'back': 5,
 'to': 6,
 'school': 7,
 'india': 8,
 'won': 9,
 'the': 10,
 'match': 11,
 'i': 12,
 'am': 13,
 'happy': 14,
 'dhoni': 15,
 'is': 16,
 'king': 17}

In [44]:
tokenizer.word_counts

OrderedDict([('go', 2),
             ('home', 1),
             ('come', 1),
             ('back', 1),
             ('to', 1),
             ('school', 1),
             ('india', 1),
             ('won', 1),
             ('the', 1),
             ('match', 1),
             ('i', 1),
             ('am', 1),
             ('happy', 1),
             ('dhoni', 1),
             ('is', 1),
             ('king', 1)])

In [45]:
tokenizer.document_count

6

In [46]:
sequences= tokenizer.texts_to_sequences(docs)
sequences

[[2, 3], [4, 5], [2, 6, 7], [8, 9, 10, 11], [12, 13, 14], [15, 16, 17]]

In [47]:
from keras.utils import pad_sequences

In [48]:
sequences=pad_sequences(sequences,padding='post')

In [49]:
sequences

array([[ 2,  3,  0,  0],
       [ 4,  5,  0,  0],
       [ 2,  6,  7,  0],
       [ 8,  9, 10, 11],
       [12, 13, 14,  0],
       [15, 16, 17,  0]], dtype=int32)

In [50]:
from keras.layers import Dense,SimpleRNN,Embedding,Flatten

In [58]:
model=Sequential()
model.add(Embedding(100,output_dim =2,input_length = 4))

model.summary()

Model: "sequential_8"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_3 (Embedding)     (None, 4, 2)              200       
                                                                 
Total params: 200 (800.00 Byte)
Trainable params: 200 (800.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [59]:
model.compile('adam','accuracy')

In [60]:
pred = model.predict(sequences)
print(pred)

1/1 [==============================] - 0s 51ms/step
[[[ 0.03919974  0.02930412]
  [ 0.04743488 -0.00382533]
  [ 0.01088306 -0.02859269]
  [ 0.01088306 -0.02859269]]

 [[ 0.02390659 -0.02555552]
  [ 0.02935303 -0.00331485]
  [ 0.01088306 -0.02859269]
  [ 0.01088306 -0.02859269]]

 [[ 0.03919974  0.02930412]
  [ 0.01441807  0.00731361]
  [ 0.03759931 -0.04005961]
  [ 0.01088306 -0.02859269]]

 [[-0.02345836 -0.00080413]
  [ 0.00153779 -0.03339237]
  [ 0.01325817 -0.04988502]
  [ 0.03016391 -0.04660282]]

 [[ 0.01808843 -0.04611614]
  [ 0.0112676   0.01725355]
  [-0.04488568 -0.02989643]
  [ 0.01088306 -0.02859269]]

 [[ 0.03936661 -0.03297433]
  [ 0.02807237 -0.00780215]
  [-0.04135778 -0.00704418]
  [ 0.01088306 -0.02859269]]]
